# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c5b51192c6ba26ef816753d8f48b3d712ccf01511d4496da5f57b487a8d34e53627efeca34ee7a355ad03abb9eec68132248e53eb3aaf9a39cf22c30b39f03f

test:
  secret_key_base: 8d150900930f7b8fc16c4051a17e5d374f72d037e9e4b6ae63ee8cb0e28a5443c4868712e0a0138456bf12037e01d21b0cbf15d60c8f71fcafd10a2e7fbafffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
